[package]
name = "my_os"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.0"            # For locks in the kernel
x86_64 = "0.14.10"        # Low-level CPU access
bootloader = "0.10.12"    # To boot the kernel
linked_list_allocator = "0.9.0" # For dynamic memory allocation

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
bootimage = "0.10.2"

